# build + redirects example
[build]
  publish = "dist2"          # output directory
  command = "npm run build" # build command

[context.production.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/webworldwebsite.html"
  status = 200
